# Generated by Django 4.2.30 on 2026-09-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre del cliente'),
        ),
    ]
