# Generated by Django 4.2.30 on 2026-09-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_remove_table_name'),
        ('orders', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcing_by', models.CharField(blank=True, max_length=60)),
                ('announcing_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='dining.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Borrador de mesa',
                'verbose_name_plural': 'Borradores de mesa',
            },
        ),
    ]
