# Generated by Django 4.2.30 on 2026-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0001_initial'),
        ('orders', '0005_tablesession_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='waiters.mesero', verbose_name='Mesero'),
        ),
        migrations.AddField(
            model_name='order',
            name='mesero_nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='Mesero (nombre)'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='waiters.mesero', verbose_name='Mesero'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('qr', 'Cliente (QR)'), ('panel', 'Panel'), ('mesero', 'Mesero (tablet)')], default='qr', max_length=10),
        ),
    ]
