# Generated by Django 4.2.30 on 2026-09-15 04:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_mesero_order_mesero_nombre_tablesession_mesero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='impresiones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='opciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Propina'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='propina_medio',
            field=models.CharField(blank=True, max_length=4, verbose_name='Medio de pago de la propina'),
        ),
    ]
