# Generated by Django 4.2.30 on 2026-09-22 22:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('shifts', '0002_turnocaja_propinas_pagadas_en_and_more'),
        ('orders', '0007_order_impresiones_orderitem_opciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparando_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='servido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='novedad',
            field=models.CharField(blank=True, choices=[('anulado', 'Anulado'), ('cortesia', 'Cortesía'), ('devolucion', 'Devolución')], max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='descuento_motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo del descuento'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.CreateModel(
            name='NovedadCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anulacion', 'Anulación'), ('cortesia', 'Cortesía'), ('devolucion', 'Devolución'), ('descuento', 'Descuento')], db_index=True, max_length=12)),
                ('producto_nombre', models.CharField(blank=True, max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('motivo', models.CharField(max_length=200)),
                ('registrado_por', models.CharField(blank=True, max_length=120)),
                ('autorizado_por', models.CharField(blank=True, max_length=120)),
                ('mesero_nombre', models.CharField(blank=True, max_length=80)),
                ('ya_preparado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='orders.orderitem')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='orders.order')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='orders.tablesession')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='shifts.turnocaja')),
            ],
            options={
                'verbose_name': 'Novedad de cuenta',
                'verbose_name_plural': 'Novedades de cuenta',
                'ordering': ['-creado'],
            },
        ),
    ]
