# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_anulado_en_order_preparando_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novedadcuenta",
            name="turno",
        ),
        migrations.RemoveField(
            model_name="tablesession",
            name="propina",
        ),
        migrations.RemoveField(
            model_name="tablesession",
            name="propina_medio",
        ),
        migrations.RemoveField(
            model_name="tablesession",
            name="reserva",
        ),
        migrations.RemoveField(
            model_name="tablesession",
            name="turno",
        ),
    ]
