# Generated by Django 4.2.30 on 2026-09-22 22:05

import apps.reservas.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dining', '0003_table_reservable_table_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Si lo apagas, el sitio web deja de ofrecer reservas.', verbose_name='Recibir reservas por internet')),
                ('confirmacion_automatica', models.BooleanField(default=True, help_text='Si hay mesa libre, la reserva queda confirmada al instante. Si lo apagas, cada reserva espera a que alguien la confirme.', verbose_name='Confirmar solas si hay cupo')),
                ('anticipacion_horas', models.PositiveIntegerField(default=2, help_text='No se puede reservar para dentro de menos de estas horas.', verbose_name='Horas mínimas de anticipación')),
                ('dias_maximo', models.PositiveIntegerField(default=45, verbose_name='Hasta cuántos días adelante')),
                ('max_personas', models.PositiveIntegerField(default=12, help_text='Los grupos más grandes se atienden por WhatsApp.', verbose_name='Máximo de personas por reserva en línea')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=20, help_text='Pasado este tiempo sin llegar, la reserva se marca para revisar como no llegó.', verbose_name='Minutos de espera')),
                ('recordar_horas_antes', models.PositiveIntegerField(default=24, verbose_name='Recordar con cuántas horas de anticipación')),
                ('whatsapp', models.CharField(blank=True, help_text='A este número llega el aviso de cada reserva nueva.', max_length=20, verbose_name='WhatsApp del restaurante')),
                ('mensaje_recordatorio', models.TextField(blank=True, default='Hola {nombre}, te esperamos {cuando} en {restaurante} para {personas}. Tu código de reserva es {codigo}. Si no puedes venir, respóndenos este mensaje. ¡Gracias!', help_text='Puedes usar {nombre}, {cuando}, {restaurante}, {personas} y {codigo}.', verbose_name='Mensaje del recordatorio')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes de reservas',
                'verbose_name_plural': 'Ajustes de reservas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('notas', models.TextField(blank=True, help_text='Lo que conviene recordar: alergias, mesa preferida, fechas especiales.', verbose_name='Notas del cliente')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('mesa', 'Por hora, con mesa'), ('dia', 'Por día, con cupo de personas')], default='mesa', max_length=6, verbose_name='Cómo se reserva')),
                ('dias', models.JSONField(default=list, help_text='0 es lunes y 6 es domingo.', verbose_name='Días')),
                ('abre', models.TimeField(verbose_name='Abre')),
                ('cierra', models.TimeField(help_text='Si cierra a medianoche o después, se entiende que es al día siguiente.', verbose_name='Cierra')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, verbose_name='Cada cuántos minutos se ofrece una hora')),
                ('duracion_minutos', models.PositiveIntegerField(default=120, help_text='Una mesa reservada a las 7:00 queda ocupada este tiempo.', verbose_name='Cuánto dura una mesa ocupada')),
                ('ultima_llegada_minutos', models.PositiveIntegerField(default=60, verbose_name='Última reserva, minutos antes de cerrar')),
                ('cupo_personas', models.PositiveIntegerField(default=0, help_text='Por día en los servicios por día. En los de mesa, 0 es sin límite aparte de las mesas.', verbose_name='Cupo de personas')),
                ('descripcion', models.CharField(blank=True, max_length=160, verbose_name='Texto para el cliente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio de reservas',
                'verbose_name_plural': 'Servicios de reservas',
                'ordering': ['orden', 'abre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=apps.reservas.models.nuevo_codigo, max_length=8, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('servicio_nombre', models.CharField(blank=True, max_length=60)),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('personas', models.PositiveIntegerField(default=2, verbose_name='Personas')),
                ('zona', models.CharField(blank=True, max_length=40, verbose_name='Zona preferida')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('arrived', 'Llegó'), ('seated', 'En la mesa'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No llegó')], db_index=True, default='pending', max_length=10)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('origen', models.CharField(choices=[('sitio', 'Página web'), ('mesa_qr', 'Menú de la mesa'), ('panel', 'Panel'), ('telefono', 'Llamada'), ('whatsapp', 'WhatsApp')], default='sitio', max_length=10)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('confirmada_por', models.CharField(blank=True, max_length=120)),
                ('recordatorio_en', models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio enviado')),
                ('llegada_en', models.DateTimeField(blank=True, null=True)),
                ('sentada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=200)),
                ('vista_en', models.DateTimeField(blank=True, null=True)),
                ('clave_envio', models.CharField(blank=True, db_index=True, max_length=64)),
                ('creada_por', models.CharField(blank=True, max_length=120)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='dining.table', verbose_name='Mesa')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.servicioreserva', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha', 'hora', 'creada_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='Motivo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(blank=True, help_text='Déjalo vacío para cerrar todo el día.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='reservas.servicioreserva', verbose_name='Solo este servicio')),
            ],
            options={
                'verbose_name': 'Día sin reservas',
                'verbose_name_plural': 'Días sin reservas',
                'ordering': ['fecha'],
            },
        ),
    ]
