# Generated by Django 4.2.30 on 2026-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioreserva',
            name='cierra',
            field=models.TimeField(help_text='Medianoche o después: al día siguiente.', verbose_name='Cierra'),
        ),
    ]
