# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_retirar_modulos"),
        ("reservas", "0002_alter_servicioreserva_cierra"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AjustesReservas",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mesa",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="servicio",
        ),
        migrations.DeleteModel(
            name="BloqueoFecha",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Reserva",
        ),
        migrations.DeleteModel(
            name="ServicioReserva",
        ),
    ]
