# Generated by Django 4.2.30 on 2026-09-13 01:28

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Turno n.º')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], db_index=True, default='abierto', max_length=10)),
                ('abierto_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Apertura')),
                ('abierto_por', models.CharField(blank=True, max_length=120, verbose_name='Abierto por')),
                ('base_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='El efectivo con el que arranca la caja.', max_digits=12, verbose_name='Base inicial de caja')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('cerrado_por', models.CharField(blank=True, max_length=120, verbose_name='Cerrado por')),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Efectivo contado al cerrar')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='Contado menos lo que debería haber. Negativo es faltante.', max_digits=12, null=True, verbose_name='Diferencia de caja')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cierre')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('total_mesas', models.PositiveIntegerField(default=0)),
                ('total_comensales', models.PositiveIntegerField(default=0)),
                ('total_facturado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('docs_aceptados', models.PositiveIntegerField(default=0)),
                ('docs_pendientes', models.PositiveIntegerField(default=0)),
                ('docs_rechazados', models.PositiveIntegerField(default=0)),
                ('costo_inventario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Costo del inventario consumido')),
                ('resumen', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Turno de caja',
                'verbose_name_plural': 'Turnos de caja',
                'ordering': ['-abierto_en'],
            },
        ),
    ]
