# Generated by Django 4.2.30 on 2026-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='propinas_pagadas_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='propinas_pagadas_por',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
