# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_retirar_modulos"),
        ("inventory", "0002_retirar_modulos"),
        ("orders", "0009_retirar_modulos"),
        ("shifts", "0002_turnocaja_propinas_pagadas_en_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TurnoCaja",
        ),
    ]
