# Generated by Django 4.2.30 on 2026-09-12 05:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_tabledraft'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('22', 'Cédula de extranjería'), ('41', 'Pasaporte'), ('cf', 'Consumidor final')], default='cf', max_length=4)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(default='Consumidor final', max_length=180)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente para facturar',
                'verbose_name_plural': 'Clientes para facturar',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura electrónica de venta'), ('doc_equivalente_pos', 'Documento equivalente POS'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito')], default='factura', max_length=24)),
                ('prefijo', models.CharField(blank=True, max_length=10)),
                ('consecutivo', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_completo', models.CharField(blank=True, db_index=True, max_length=30)),
                ('cufe', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='CUFE')),
                ('estado', models.CharField(choices=[('pendiente_envio', 'Pendiente de envío'), ('enviada', 'Enviada al proveedor'), ('aceptada_dian', 'Aceptada por la DIAN'), ('rechazada', 'Rechazada'), ('en_contingencia', 'En contingencia'), ('anulada', 'Anulada')], db_index=True, default='pendiente_envio', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('xml_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('respuesta_pt', models.JSONField(blank=True, default=dict, verbose_name='Respuesta cruda del proveedor')),
                ('lineas', models.JSONField(blank=True, default=list)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('impuestos_detalle', models.JSONField(blank=True, default=dict)),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_transmision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('proximo_reintento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='billing.clientefiscal')),
                ('documento_referencia', models.ForeignKey(blank=True, help_text='La factura que corrige o anula esta nota.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='billing.documentofiscal')),
            ],
            options={
                'verbose_name': 'Documento fiscal',
                'verbose_name_plural': 'Documentos fiscales',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=180, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=180, verbose_name='Nombre comercial')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='DV')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=80, verbose_name='Departamento')),
                ('correo_facturacion', models.EmailField(blank=True, max_length=254, verbose_name='Correo de facturación')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('regimen', models.CharField(choices=[('iva', 'Responsable de IVA'), ('inc', 'Responsable de INC (restaurantes)'), ('no_responsable', 'No responsable')], default='inc', max_length=20, verbose_name='Régimen')),
                ('precios_incluyen_impuesto', models.BooleanField(default=True, verbose_name='Los precios del menú ya incluyen impuesto')),
                ('certificado_ref', models.TextField(blank=True, verbose_name='Certificado (referencia cifrada)')),
                ('certificado_vence', models.DateField(blank=True, null=True, verbose_name='Vencimiento del certificado')),
                ('proveedor', models.CharField(default='simulado', help_text="Identificador del PT: 'simulado' mientras no haya uno real.", max_length=40, verbose_name='Proveedor tecnológico')),
                ('credenciales_pt', models.TextField(blank=True, verbose_name='Credenciales del PT (cifradas)')),
                ('estado_habilitacion', models.CharField(choices=[('no_habilitado', 'No habilitado'), ('en_pruebas', 'En pruebas con el proveedor'), ('habilitado', 'Habilitado'), ('rechazado', 'Rechazado')], default='no_habilitado', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos fiscales',
                'verbose_name_plural': 'Datos fiscales',
            },
        ),
        migrations.CreateModel(
            name='ResolucionNumeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura electrónica de venta'), ('doc_equivalente_pos', 'Documento equivalente POS'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito')], default='factura', max_length=24)),
                ('numero_resolucion', models.CharField(max_length=40, verbose_name='Número de resolución')),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('prefijo', models.CharField(blank=True, max_length=10)),
                ('rango_desde', models.PositiveIntegerField()),
                ('rango_hasta', models.PositiveIntegerField()),
                ('consecutivo_actual', models.PositiveIntegerField(help_text='El último número usado. El siguiente documento lleva este + 1.')),
                ('clave_tecnica', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='billing.empresafiscal')),
            ],
            options={
                'verbose_name': 'Resolución de numeración',
                'verbose_name_plural': 'Resoluciones de numeración',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=60)),
                ('resultado', models.CharField(default='ok', max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='billing.documentofiscal')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('INC', 'Impuesto Nacional al Consumo'), ('EXENTO', 'Exento')], default='INC', max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Tarifa (%)')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='catalog.category', verbose_name='Solo para esta categoría')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['categoria__id', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='billing.resolucionnumeracion'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='orders.tablesession', verbose_name='Cuenta de mesa'),
        ),
    ]
