# Generated by Django 4.2.30 on 2026-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_documentofiscal_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='medio_pago',
            field=models.CharField(choices=[('10', 'Efectivo'), ('49', 'Tarjeta débito'), ('48', 'Tarjeta crédito'), ('47', 'Transferencia')], default='10', max_length=4, verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='qr_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Enlace de consulta DIAN'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='referencia_pt',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='resolucionnumeracion',
            name='id_rango_proveedor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='xml_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
