# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_documentofiscal_medio_pago_documentofiscal_qr_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentofiscal",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="documentofiscal",
            name="documento_referencia",
        ),
        migrations.RemoveField(
            model_name="documentofiscal",
            name="resolucion",
        ),
        migrations.RemoveField(
            model_name="documentofiscal",
            name="sesion",
        ),
        migrations.RemoveField(
            model_name="documentofiscal",
            name="turno",
        ),
        migrations.RemoveField(
            model_name="logauditoria",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="resolucionnumeracion",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="impuesto",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="ClienteFiscal",
        ),
        migrations.DeleteModel(
            name="DocumentoFiscal",
        ),
        migrations.DeleteModel(
            name="LogAuditoria",
        ),
        migrations.DeleteModel(
            name="EmpresaFiscal",
        ),
        migrations.DeleteModel(
            name="ResolucionNumeracion",
        ),
        migrations.DeleteModel(
            name="Impuesto",
        ),
    ]
