# Generated by Django 4.2.30 on 2026-09-12 07:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=4)),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('forma_pago', models.CharField(choices=[('hora', 'Por hora'), ('mes', 'Salario mensual')], default='hora', max_length=10, verbose_name='Forma de pago')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lo que cuesta una hora de esta persona. Sirve para estimar el costo del turno.', max_digits=12, verbose_name='Valor de la hora')),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Salario mensual')),
                ('codigo', models.CharField(blank=True, max_length=8, verbose_name='Código para marcar')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('cerrado_automatico', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='staffing.empleado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-entrada'],
            },
        ),
    ]
