# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0001_initial"),
        ("waiters", "0003_retirar_modulos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turno",
            name="empleado",
        ),
        migrations.DeleteModel(
            name="Empleado",
        ),
        migrations.DeleteModel(
            name="Turno",
        ),
    ]
