# Generated by Django 4.2.30 on 2026-09-22 22:05

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerancia_caja', models.DecimalField(decimal_places=2, default=Decimal('2000'), help_text='Diferencias menores a esto se consideran vueltas y redondeos.', max_digits=12, verbose_name='Diferencia de caja que no se reporta')),
                ('inventario_pct', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, verbose_name='Consumo real sobre el teórico que se reporta (%)')),
                ('anulaciones_por_turno', models.PositiveIntegerField(default=5, verbose_name='Anulaciones por turno que se reportan')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='Descuento excepcional desde (%)')),
                ('cortesias_pct', models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=5, verbose_name='Cortesías sobre ventas que se reportan (%)')),
                ('compra_alza_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='Alza de precio de compra que se reporta (%)')),
                ('food_cost_objetivo', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=5, verbose_name='Food cost objetivo (%)')),
                ('margen_caida_puntos', models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=5, verbose_name='Caída de margen que se reporta (puntos)')),
                ('cocina_minutos', models.PositiveIntegerField(default=25, verbose_name='Minutos de cocina que se consideran demora')),
                ('turno_horas', models.PositiveIntegerField(default=16, verbose_name='Horas de turno abierto que se reportan')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes de Cloudin Control',
                'verbose_name_plural': 'Ajustes de Cloudin Control',
            },
        ),
        migrations.CreateModel(
            name='AlertaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inventario', 'Inventario'), ('ventas', 'Ventas'), ('caja', 'Caja'), ('anulaciones', 'Anulaciones'), ('descuentos', 'Descuentos'), ('cortesias', 'Cortesías'), ('devoluciones', 'Devoluciones'), ('mermas', 'Mermas'), ('recetas', 'Recetas'), ('compras', 'Compras'), ('costos', 'Costos'), ('empleados', 'Empleados'), ('turnos', 'Turnos'), ('pedidos', 'Pedidos'), ('cocina', 'Tiempos de cocina'), ('reservas', 'Reservas')], db_index=True, max_length=16, verbose_name='Tipo')),
                ('severidad', models.CharField(choices=[('info', 'Para tener en cuenta'), ('warning', 'Revisar pronto'), ('critical', 'Revisar hoy')], db_index=True, default='info', max_length=10, verbose_name='Severidad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Qué pasó')),
                ('recomendacion', models.TextField(blank=True, verbose_name='Qué revisar')),
                ('impacto_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cuánta plata podría estar en juego. Es una estimación, no una pérdida confirmada.', max_digits=14, verbose_name='Impacto estimado')),
                ('categoria_fuga', models.CharField(blank=True, choices=[('caja', 'Diferencias de caja'), ('inventario', 'Inventario real vs. teórico'), ('mermas', 'Mermas'), ('anulaciones', 'Anulaciones'), ('descuentos', 'Descuentos excepcionales'), ('cortesias', 'Cortesías'), ('devoluciones', 'Devoluciones'), ('recetas', 'Diferencias de receta'), ('compras', 'Compras más caras'), ('otras', 'Otras diferencias')], db_index=True, max_length=14)),
                ('entidad_tipo', models.CharField(blank=True, max_length=30)),
                ('entidad_id', models.CharField(blank=True, max_length=40)),
                ('enlace', models.CharField(blank=True, max_length=200, verbose_name='Dónde verlo')),
                ('periodo_desde', models.DateField(blank=True, db_index=True, null=True)),
                ('periodo_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('new', 'Nueva'), ('reviewed', 'En revisión'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], db_index=True, default='new', max_length=10, verbose_name='Estado')),
                ('detectada_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('revisada_por', models.CharField(blank=True, max_length=120)),
                ('nota', models.TextField(blank=True, verbose_name='Nota de quien la revisó')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('huella', models.CharField(max_length=160, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta de control',
                'verbose_name_plural': 'Alertas de control',
                'db_table': 'control_alert',
                'ordering': ['-detectada_en'],
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('duracion_ms', models.PositiveIntegerField(default=0)),
                ('alertas_nuevas', models.PositiveIntegerField(default=0)),
                ('alertas_actualizadas', models.PositiveIntegerField(default=0)),
                ('por_detector', models.JSONField(blank=True, default=dict)),
                ('usuario', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Análisis de control',
                'verbose_name_plural': 'Análisis de control',
                'ordering': ['-momento'],
            },
        ),
    ]
