# Generated by Django 4.2.30 on 2026-09-11 23:19

import apps.dining.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número de mesa')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Nombre / ubicación')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='Puestos')),
                ('token', models.CharField(default=apps.dining.models.generate_table_token, editable=False, max_length=32, unique=True, verbose_name='Token QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
    ]
