# Generated by Django 4.2.30 on 2026-09-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
    ]
