# Generated by Django 4.2.30 on 2026-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_remove_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reservable',
            field=models.BooleanField(default=True, verbose_name='Se puede reservar'),
        ),
        migrations.AddField(
            model_name='table',
            name='zona',
            field=models.CharField(blank=True, max_length=40, verbose_name='Zona'),
        ),
    ]
