# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0003_table_reservable_table_zona"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="reservable",
        ),
    ]
