# Generated by Django 4.2.30 on 2026-09-11 23:19

import apps.tenants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador en el subdominio: lajoya -> lajoya.cloudin.app', max_length=60, unique=True, verbose_name='Subdominio')),
                ('api_key', models.CharField(default=apps.tenants.models.generate_api_key, editable=False, max_length=64, unique=True)),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
                ('legal_name', models.CharField(blank=True, max_length=160, verbose_name='Razón social')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('db_name', models.CharField(blank=True, editable=False, max_length=80)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('provisioned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador del restaurante'), ('staff', 'Mesero / cajero')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de restaurante',
                'verbose_name_plural': 'Usuarios de restaurante',
            },
        ),
    ]
