# Generated by Django 4.2.30 on 2026-09-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='password_actualizada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='password_cifrada',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
