# Generated by Django 4.2.30 on 2026-09-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmembership_password_actualizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='Sitio web del restaurante'),
        ),
    ]
