# Generated by Django 4.2.30 on 2026-09-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='site_last_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
