# Generated by Django 4.2.30 on 2026-09-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_site_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='table_page_path',
            field=models.CharField(default='/mesa.html', max_length=120, verbose_name='Página de pedidos en mesa'),
        ),
    ]
