# Generated by Django 4.2.30 on 2026-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_table_page_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modo_servicio',
            field=models.CharField(choices=[('autoservicio', 'Autoservicio: el cliente pide desde el QR'), ('meseros', 'Meseros: el mesero toma el pedido en la tablet'), ('mixto', 'Ambos: QR y meseros a la vez')], default='autoservicio', max_length=14, verbose_name='Cómo se toman los pedidos'),
        ),
    ]
