# Generated by Django 4.2.30 on 2026-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_modo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='menu_fuente',
            field=models.URLField(blank=True, max_length=500, verbose_name='Archivo de la carta'),
        ),
    ]
