# Generated by Django 4.2.30 on 2026-09-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_tenant_menu_fuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceptacionLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('aceptado_en', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_legales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceptación de términos',
                'verbose_name_plural': 'Aceptaciones de términos',
                'ordering': ['-aceptado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='aceptacionlegal',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='una_aceptacion_por_version'),
        ),
    ]
