# Generated by Django 5.2.17 on 2026-09-26 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_aceptacionlegal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list, verbose_name='Otros sitios autorizados'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='menu_page',
            field=models.URLField(blank=True, max_length=500, verbose_name='Página del menú (QR)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('menu', 'Menú digital'), ('completo', 'Cloudin completo')], default='menu', max_length=12, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño del restaurante'), ('admin', 'Administrador del restaurante'), ('staff', 'Mesero / cajero')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Para qué es, p. ej. «Portátil de Juan».', max_length=80, verbose_name='Nombre')),
                ('prefix', models.CharField(editable=False, max_length=12)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de API',
                'verbose_name_plural': 'Tokens de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
