# Generated by Django 5.2.17 on 2026-09-26 04:54

import apps.business.models
import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOpeningHours',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('history_user_name', models.CharField(blank=True, max_length=150, verbose_name='Hecho por')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('opens', models.TimeField(verbose_name='Abre')),
                ('closes', models.TimeField(verbose_name='Cierra')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Horario',
                'verbose_name_plural': 'historical Horarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRestaurantSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('history_user_name', models.CharField(blank=True, max_length=150, verbose_name='Hecho por')),
                ('logo', models.TextField(blank=True, max_length=100, verbose_name='Logo')),
                ('cover', models.TextField(blank=True, max_length=100, verbose_name='Portada')),
                ('color_primary', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color principal')),
                ('color_secondary', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color secundario')),
                ('color_background', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color de fondo')),
                ('color_text', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color del texto')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='Frase corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('welcome_message', models.CharField(blank=True, max_length=200, verbose_name='Mensaje de bienvenida')),
                ('whatsapp', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+57\\d{10}$', 'Escribe el número con +57 y 10 dígitos (ej. +573001234567).')], verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+57\\d{10}$', 'Escribe el número con +57 y 10 dígitos (ej. +573001234567).')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('maps_url', models.URLField(blank=True, max_length=500, verbose_name='Enlace de Google Maps')),
                ('instagram', models.URLField(blank=True, max_length=300, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, max_length=300, verbose_name='Facebook')),
                ('tiktok', models.URLField(blank=True, max_length=300, verbose_name='TikTok')),
                ('services', models.JSONField(blank=True, default=dict, verbose_name='Servicios')),
                ('payment_methods', models.JSONField(blank=True, default=list, verbose_name='Medios de pago')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Datos del negocio',
                'verbose_name_plural': 'historical Datos del negocio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('logo', models.ImageField(blank=True, upload_to=apps.business.models.ruta_marca, verbose_name='Logo')),
                ('cover', models.ImageField(blank=True, upload_to=apps.business.models.ruta_marca, verbose_name='Portada')),
                ('color_primary', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color principal')),
                ('color_secondary', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color secundario')),
                ('color_background', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color de fondo')),
                ('color_text', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color en formato #RRGGBB.')], verbose_name='Color del texto')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='Frase corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('welcome_message', models.CharField(blank=True, max_length=200, verbose_name='Mensaje de bienvenida')),
                ('whatsapp', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+57\\d{10}$', 'Escribe el número con +57 y 10 dígitos (ej. +573001234567).')], verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+57\\d{10}$', 'Escribe el número con +57 y 10 dígitos (ej. +573001234567).')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('maps_url', models.URLField(blank=True, max_length=500, verbose_name='Enlace de Google Maps')),
                ('instagram', models.URLField(blank=True, max_length=300, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, max_length=300, verbose_name='Facebook')),
                ('tiktok', models.URLField(blank=True, max_length=300, verbose_name='TikTok')),
                ('services', models.JSONField(blank=True, default=dict, verbose_name='Servicios')),
                ('payment_methods', models.JSONField(blank=True, default=list, verbose_name='Medios de pago')),
                ('menu_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=0, verbose_name='Paso del asistente')),
                ('onboarding_done_at', models.DateTimeField(blank=True, null=True, verbose_name='Asistente terminado')),
                ('import_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'Datos del negocio',
                'verbose_name_plural': 'Datos del negocio',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('opens', models.TimeField(verbose_name='Abre')),
                ('closes', models.TimeField(verbose_name='Cierra')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day', 'opens'],
                'constraints': [models.CheckConstraint(condition=models.Q(('day__lte', 6)), name='horario_dia_valido'), models.CheckConstraint(condition=models.Q(('opens', models.F('closes')), _negated=True), name='horario_abre_distinto_de_cierra')],
            },
        ),
    ]
