# Generated by Django 5.2.17 on 2026-09-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("contenido", models.BinaryField()),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de contenido"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
            },
        ),
    ]
