# Generated by Django 4.2.30 on 2026-09-13 01:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0005_tablesession_turno'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('principal', models.BooleanField(default=False, verbose_name='Es la principal')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['-principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('posicion', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de insumo',
                'verbose_name_plural': 'Categorías de insumo',
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=40, verbose_name='Factura del proveedor')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de la compra')),
                ('medio_pago', models.CharField(choices=[('caja', 'Caja / efectivo'), ('banco', 'Cuenta bancaria'), ('tarjeta', 'Tarjeta del negocio'), ('credito', 'Crédito con el proveedor')], default='caja', max_length=10, verbose_name='Se pagó con')),
                ('cuenta', models.CharField(blank=True, help_text='Cuál cuenta bancaria o tarjeta, para poder cruzarlo después.', max_length=80, verbose_name='Cuenta o tarjeta')),
                ('vence', models.DateField(blank=True, null=True, verbose_name='Vence el (si es a crédito)')),
                ('pagada', models.BooleanField(default=True, verbose_name='Ya está pagada')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('registrada', 'Registrada'), ('anulada', 'Anulada')], db_index=True, default='borrador', max_length=12)),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('usuario', models.CharField(blank=True, max_length=120, verbose_name='Registrada por')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('registrada_en', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventory.bodega', verbose_name='Entra a la bodega')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(blank=True, max_length=120, verbose_name='Quién contó')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('borrador', 'En conteo'), ('aplicado', 'Aplicado')], db_index=True, default='borrador', max_length=10)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('diferencia_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventory.bodega')),
            ],
            options={
                'verbose_name': 'Conteo físico',
                'verbose_name_plural': 'Conteos físicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Código de referencia')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre')),
                ('unidad_compra', models.CharField(default='kg', help_text='Como se la vende el proveedor: bulto, caja, kg…', max_length=40, verbose_name='Unidad de compra')),
                ('unidad_consumo', models.CharField(choices=[('g', 'Gramos (g)'), ('kg', 'Kilogramos (kg)'), ('ml', 'Mililitros (ml)'), ('l', 'Litros (L)'), ('und', 'Unidades'), ('porcion', 'Porciones')], default='g', help_text='Como la usa la receta.', max_length=10, verbose_name='Unidad de consumo')),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=Decimal('1000'), help_text='Un bulto de 50 kg que se consume en gramos: 50000.', max_digits=14, verbose_name='Unidades de consumo por unidad de compra')),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo promedio por unidad de consumo')),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Último precio de compra (por unidad de compra)')),
                ('ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de la última compra')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Por debajo de esto, el panel avisa que hay que reponer.', max_digits=14, verbose_name='Stock mínimo')),
                ('perecedero', models.BooleanField(default=False, help_text='Si lo es, se controla por lote y vencimiento.', verbose_name='Perecedero')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='inventory.categoriainsumo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='Lote')),
                ('vence', models.DateField(blank=True, null=True, verbose_name='Vence')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.bodega')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['vence', 'creado'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre o razón social')),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT / cédula')),
                ('contacto', models.CharField(blank=True, max_length=120, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de crédito')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, verbose_name='Nombre')),
                ('es_subreceta', models.BooleanField(default=False, help_text='No se vende sola: se usa dentro de otras recetas.', verbose_name='Es una subreceta (producto intermedio)')),
                ('rendimiento', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Cuántas porciones o unidades salen de preparar la receta una vez.', max_digits=12, verbose_name='Rendimiento')),
                ('unidad_rendimiento', models.CharField(default='porcion', max_length=20, verbose_name='Unidad del rendimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Preparación / notas')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='catalog.product', verbose_name='Producto del menú')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, verbose_name='Cantidad')),
                ('nota', models.CharField(blank=True, max_length=160, verbose_name='Nota')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='en_recetas', to='inventory.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receta')),
                ('subreceta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usada_en', to='inventory.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra a proveedor'), ('ajuste_mas', 'Ajuste positivo'), ('dev_cliente', 'Devolución de cliente'), ('traslado_in', 'Traslado recibido'), ('conteo_mas', 'Conteo físico (sobrante)'), ('produccion', 'Producción de subreceta'), ('venta', 'Venta (receta)'), ('ajuste_menos', 'Ajuste negativo'), ('merma', 'Merma o desperdicio'), ('dev_proveedor', 'Devolución a proveedor'), ('traslado_out', 'Traslado enviado'), ('conteo_menos', 'Conteo físico (faltante)')], db_index=True, max_length=16)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Cantidad (unidad de consumo)')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('saldo_cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('saldo_costo_promedio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('usuario', models.CharField(blank=True, max_length=120, verbose_name='Quién lo registró')),
                ('momento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.bodega')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.compra')),
                ('conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.conteo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.lote')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='orders.order')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='shifts.turnocaja')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-momento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='inventory.proveedor', verbose_name='Proveedor habitual'),
        ),
        migrations.CreateModel(
            name='ConteoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esperado', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('contado', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.conteo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Línea de conteo',
                'verbose_name_plural': 'Líneas de conteo',
                'ordering': ['insumo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, verbose_name='Cantidad (unidad de compra)')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor por unidad de compra')),
                ('lote', models.CharField(blank=True, max_length=40, verbose_name='Lote')),
                ('vence', models.DateField(blank=True, null=True, verbose_name='Vence')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Línea de compra',
                'verbose_name_plural': 'Líneas de compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventory.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventory.bodega')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'ordering': ['insumo__nombre'],
                'unique_together': {('insumo', 'bodega')},
            },
        ),
    ]
