# Generated by Django 4.2.30 on 2026-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('usuario', models.CharField(help_text='Con esto entra en la tablet. Sin espacios; no distingue mayúsculas.', max_length=40, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesero', to='staffing.empleado', verbose_name='Empleado en Cloudin Employees')),
            ],
            options={
                'verbose_name': 'Mesero',
                'verbose_name_plural': 'Meseros',
                'ordering': ['nombre'],
            },
        ),
    ]
