# Generated by Django 4.2.30 on 2026-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='clave_cifrada',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
