# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waiters", "0002_mesero_clave_cifrada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mesero",
            name="empleado",
        ),
    ]
