# Generated by Django 4.2.30 on 2026-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clave_externa',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='clave_externa',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='menu/%Y/%m/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='product',
            name='opciones',
            field=models.JSONField(blank=True, default=list, verbose_name='Toppings y opciones'),
        ),
        migrations.AddField(
            model_name='product',
            name='permite_observacion',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente o el mesero pueden escribir «sin cebolla», etc.', verbose_name='Permitir observación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Imagen (URL)'),
        ),
    ]
