# Generated by Django 4.2.30 on 2026-09-15 04:15

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_clave_externa_product_clave_externa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=apps.catalog.models.ruta_foto, verbose_name='Foto'),
        ),
    ]
