# Generated by Django 4.2.30 on 2026-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
