# Generated by Django 4.2.30 on 2026-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='secciones',
            field=models.JSONField(blank=True, default=list, verbose_name='Cartas donde aparece'),
        ),
    ]
