# Generated by Django 5.2.17 on 2026-09-26 04:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_v1_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID público')),
                ('history_user_name', models.CharField(blank=True, max_length=150, verbose_name='Hecho por')),
                ('key', models.SlugField(max_length=60, verbose_name='Clave')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.TextField(blank=True, max_length=100, verbose_name='Imagen')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('secciones', models.JSONField(blank=True, default=list, verbose_name='Cartas donde aparece')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Archivada')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Categoría',
                'verbose_name_plural': 'historical Categorías',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID público')),
                ('history_user_name', models.CharField(blank=True, max_length=150, verbose_name='Hecho por')),
                ('key', models.SlugField(max_length=60, verbose_name='Clave')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Imagen (URL)')),
                ('imagen', models.TextField(blank=True, max_length=100, verbose_name='Foto')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='Código interno')),
                ('prep_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (min)')),
                ('tax_type', models.CharField(blank=True, choices=[('INC8', 'INC 8 % (impoconsumo)'), ('IVA19', 'IVA 19 %'), ('EXENTO', 'Exento')], max_length=8, verbose_name='Impuesto')),
                ('base_label', models.CharField(blank=True, max_length=40, verbose_name='Nombre de la presentación base')),
                ('permite_observacion', models.BooleanField(default=True, help_text='Si está activo, el cliente o el mesero pueden escribir «sin cebolla», etc.', verbose_name='Permitir observación')),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='category',
            name='clave_externa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='clave_externa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opciones',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.SlugField(max_length=60, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.menu', verbose_name='Menú'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID público'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.SlugField(max_length=60, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID público'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('menu', 'key'), name='categoria_clave_unica_por_menu'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='producto_clave_unica_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', False), ('is_available', False), _connector='OR'), name='producto_sin_precio_no_disponible'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='producto_precio_no_negativo'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='menu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.menu', verbose_name='Menú'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category', verbose_name='Categoría'),
        ),
    ]
